
# destination is relative to the source folder
# ./ for current directory
# ../ for parent directory
# start with / for root directory
tasks:
  - name: Organize Downloads
    type: file-organization
    source: ./
    rules: 
      - extension: .jpg
        destination: /images
      - extension: .pdf
        destination: /documents
# backup:
#   - name: Backup Important Files
#     type: incremental-file # incremental-image, full-file, full-image
#     schedule: daily # weekly, monthly
#     retention: 7 # number of days to keep backups
#     connection:
#       server: http://your-backup-server:55414
#       username: foo
#       password: bar
#     directories:
#       - /path/to/your/important/directory
#       - /path/to/another/important/directory